config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "dashboards#index"
  # root "carts#show"
  resources :categories , only: [:index]
  resources :sub_categories
  resources :dashboards
  
  resources :products do
     get '/page/:page', action: :index, on: :collection
  end

  resources :users
  post '/auth/login' , to: 'authentication#login'
  
  resources :carts
  resources :product_carts
  resources :orders
  resources :order_items  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products ,through: :product_carts, dependent: :destroy
  has_many :product_carts , dependent: :destroy

  

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :sub_categories , dependent: :destroy
end

app/models/order.rb
# class Order < ApplicationRecord
   
#    belongs_to :user
#    has_many :order_items , dependent: :destroy
#    # enum :status, {paid:1, not_paid:0} 

# end

app/models/order_item.rb
# class OrderItem < ApplicationRecord

#    belongs_to :order
#    belongs_to :product

#    after_create :add
   
#    def add
    
#    	 price = order.order_items.map{|p| p.product.price}
#    	 order.total_amount = price.sum
#    	 puts "#{order.total_amount}"
#    	 order.save
   	 
#    end
# end

app/models/product.rb
class Product < ApplicationRecord
   has_one_attached :image # , dependent: :destroy
   belongs_to :sub_category
   # paginates_per 15
   has_many :product_carts , dependent: :destroy
   has_many :carts ,through: :product_carts, dependent: :destroy
end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
    belongs_to :category
    has_many :products , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :cart
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :add

   def add
      Cart.create(user_id: self.id)       
   end   
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
   before_action :authenticate_user! 
   # skip_before_action :verify_authenticity_token  
 
  def index
    cart = Cart.all
    render json: cart
  end
  def show
    @product_carts = current_user.cart.product_carts
    # if params[:cart_id].present?
    #   cart = Cart.find(params[:id])
    # end
    # render json: cart
  end
  def create
   cart = Cart.new(cart_params)
    if cart.save
      render json: cart
    else
      render :new
    end
  end 
  def update
    
    cart = Cart.find(params[:id])
    if cart.update(cart_params)
      render json: cart
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    cart = Cart.find(params[:id])
    cart.destroy
    render json: {message: 'cart deleted successfully'}
  end
  private
  def cart_params
    params.require(:cart).permit(:user_id )
  end








  # def add_to_cart
  #   @product = Product.find(params[:product_id])
  #   @cart_product = user.cart.find_by(product_id: @product.id)
  #   if @cart_product
  #     @cart_product.quantity += 1
  #   else
  #     @cart_product = user.cart.build(product_id: @product.id)
  #   end
  #   @cart_product.save
  #   redirect_to cart_path
  # end
  # def remove_from_cart
  #   @cart_product = user.cart.find(params[:id])
  #   @cart_product.destroy
  #   redirect_to cart_path
  # end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
   def index
      if params[:sub_category_id].present?
         @products = SubCategory.find(params[:sub_category_id]).products
      else
         @products=Product.all
      end
      @categories = Category.includes(:sub_categories).all
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # include JsonWebToken 
  # before_action :authenticate_request, only: [:index, :show, :update, :destroy] 
  skip_before_action :verify_authenticity_token

  def index
    @user = User.all
    render json: @user
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # token = jwt_encode(user_id: @user.id)
      render json: @user, status: :created
    else
      render json: @user.errors.full_messages
    end
  end 

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render json: @user
    else
      render  json: @user.errors.full_messages
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    render json: {message: 'user deleted successfully'}
  end

  private

  def user_params
    params.permit(:name, :address, :contact, :username , :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2">
      <!-- Column -->
    <%= link_to 'All Categories', dashboards_path, class: "btn btn-secondary mb-2" , style: 'margin-left: -56px ; width:195px ; color:white' %>
    <% @categories.each do |category| %>
    <div class="dropdown mb-2">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style="margin-left: -69px , height:200px;width:200px;margin-left: -60px">
    <%= category.name %>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <% category.sub_categories.each do |sub_category| %>
    <li> <%= link_to sub_category.name, dashboards_path(sub_category_id: sub_category.id) %></li>
    <!-- <li><a class="dropdown-item" href="#"><%#= sub_category.name %></a></li> -->
    <% end %>
    </ul>
    </div>
    <% end %>
      <!--  -->
    </div>
    <div class="col-lg-10">
       <div class="container-fluid">
       <div class="row mx-auto">
       <% @products.each do |product| %>
       <div class="card mx-auto mb-3" style="width: 18rem;">
       <!-- <img src= <%= product.image %> class="card-img-top" alt="..."> -->
       <% if product.image.attached? %>
        <%= image_tag(product.image , size: "250") %>
       <% end %>
       <div class="card-body">
       <h5 class="card-title"><%= product.name %></h5>
       <p class="card-text"><b>₹ <%= product.price %>/-</b></p>
       <!-- <form action="/" method="POST">
        <input hidden type="text" name="product">
 -->
       <a href="#" aria-current="page">
        <%= link_to "Add To Cart" ,product_carts_path(product_cart: { product_id: product.id, quantity: 1 }), method: :post %>
       </a>
      </div>
      </div>
      <% end %>
      </div>
      </div>
    </div>
  </div>
</div>